### ISSUE TITLE
"The Dragon Book"

### ISSUE THREAD

**Issue by tombusby** [steshaw/plt#13]
In terms of compiler construction books, Compilers: Principles, Techniques, and Tools should definitely be included. It's a definitive classic in the area.

https://en.wikipedia.org/wiki/Compilers:_Principles,_Techniques,_and_Tools

**Comment by steshaw** [comment]
That's true. I guess I didn't include it because I didn't particularly enjoy it. There are other books like Modern Compiler Design and Advanced Compiler Design and Implementation. Perhaps a link to other resources such as https://gcc.gnu.org/wiki/ListOfCompilerBooks would be useful? These days I'm happy to avoid learning all the details of CPU optimisations by using LLVM.

Happy to accept pull requests.
